include: 
  - local: 'templates/base-template.yml'
  - local: 'templates/config-job-template.yml'
  - local: 'templates/config-destroy-job-template.yml'
  - local: 'templates/network-job-template.yml'
  - local: 'templates/network-destroy-job-template.yml'
  - local: 'templates/iam-job-template.yml'
  - local: 'templates/iam-destroy-job-template.yml'
  - local: 'templates/security-group-job-template.yml'
  - local: 'templates/security-group-destroy-job-template.yml'
  - local: 'templates/cloudtrail-job-template.yml'
  - local: 'templates/cloudtrail-destroy-job-template.yml'

variables:
  VAULT_URL: https://vault.onwalk.net
  VAULT_PATH: aws
  VAULT_SECRET: aws 
  TF_STATE_KEY: test
  TF_STATE_S3: devops-velero

  env: Dev
  region: cn-northwest-1
  az: cn-northwest-1a
  application: 
  businessunit: 
  appowner: 
  email: 

  vpc_cidr: "10.25.28.0/23"
  subnet_web_route: "0.0.0.0/0"
  subnet_web_cidr: "10.25.28.0/27,10.25.28.32/27"
  subnet_dbs_route: "192.168.40.0/24"
  subnet_dbs_cidr: "10.25.29.0/27,10.25.29.32/27"

  console_user: "tf-console-user-dev-01"
  cli_user: "tf-cli-user-dev-01"

  sns_topic_name: 'cloudtrail-sns'
  s3_bucket_name: '
  kms_key_arn: 'arn:aws-cn:kms:cn-northwest-1::key/aa80eacf-64bf-452c-a8ce-517cef0a02e5'
  s3_key_prefix: 'null'
