config-destroy-job:
  stage: destroy
  script:
    - make -C config destroy
  needs:
    - config-apply-job
  dependencies:
    - config-apply-job
  retry:
    max: 2
    when: script_failure
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
