build-image-job:
  stage: build
  image:
    name: artifact.onwalk.net/k8s/kaniko-executor:debug 
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"artifact.onwalk.net/k8s\":{\"auth\":\"$(printf "%s:%s" "admin" "${PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "artifact.onwalk.net/k8s/podinfo:${canary_version}"

build-chart-job:
  stage: build
  variables:
    HELM_EXPERIMENTAL_OCI: 1
  script:
    - helm repo add sync --username=admin --password="${PASSWORD}" https://artifact.onwalk.net/chartrepo/k8s 
    - helm package chart/
    - helm cm-push rust-axum-demo-0.1.1.tgz sync
