name: Build Docker Image with Kaniko

on:
  workflow_call:
    inputs:
      registry_addr:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
    secrets:
      artifactory_sa:
        required: true
      artifactory_pw:
        required: true

jobs:
  image-build-job:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ${{ inputs.registry_addr }}
      IMAGE_REPO_USER: ${{ secrets.artifactory_sa }}
      IMAGE_REPO_PASSWORD: ${{ secrets.artifactory_pw }}
      IMAGE_TAG: ${{ inputs.image_tag }}
      IMAGE_NAME: ${{ inputs.image_name }}
      IMAGE_FULL_NAME: ${{ inputs.registry_addr }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
      DOCKERFILE_PATH: ${{ inputs.dockerfile_path }}

  alpine-awscli-python3:
    runs-on: ubuntu-latest
    name: Build alpine-awscli-python3 base image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push alpine-awscli-python3 image'
        uses: aevea/action-kaniko@master
        with:
          tag: ${{ env.IMAGE_TAG }}
          image: ${{ env.IMAGE_NAME }}
          build_file: 'Dockerfile'
          path: ${{ env.DOCKERFILE_PATH }}
          registry: ${{ env.IMAGE_REPO }}
          username: ${{ env.IMAGE_REPO_USER }}
          password: ${{ env.IMAGE_REPO_PASSWORD }}
          cache: true
          cache_registry: cache
