name: Build Docker Image with Kaniko

on:
  workflow_call:
    inputs:
      registry_addr:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
    secrets:
      artifactory_sa:
        required: true
      artifactory_pw:
        required: true

jobs:
  image_build_job:
    runs-on: ubuntu-latest
    env:
      REGISTRY_REPO_USER: ${{ secrets.artifactory_sa }}
      REGISTRY_REPO_PASSWORD: ${{ secrets.artifactory_pw }}
      DOCKER_IMAGE_FULL_NAME: ${{ inputs.registry_addr }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
      DOCKERFILE_PATH: ${{ inputs.dockerfile_path }}
    container:
      image: artifact.onwalk.net/public/base/alpine-image-builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kaniko Auth config for Docker registry v1
        run: sh /kaniko/setup-kaniko-auth.sh ${{ inputs.registry_addr }} ${{ secrets.artifactory_sa }} ${{ secrets.artifactory_pw }} true

      - name: Build Docker Image with Kaniko
        run: |
          echo "Building image: ${{ env.DOCKER_IMAGE_FULL_NAME }}"
          export GOOGLE_APPLICATION_CREDENTIALS=/kaniko/.docker/config.json
          /kaniko/executor \
              --dockerfile ${{ env.DOCKERFILE_PATH }}/Dockerfile \
              --destination "${{ env.DOCKER_IMAGE_FULL_NAME }}"  \
              --context ${{ env.DOCKERFILE_PATH }}
