name: Build Docker Image with Kaniko

on:
  workflow_call:
    inputs:
      registry_addr:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
    secrets:
      artifactory_sa:
        required: true
      artifactory_pw:
        required: true

jobs:
  image-build-job:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ${{ inputs.registry_addr }}
      IMAGE_REPO_USER: ${{ secrets.artifactory_sa }}
      IMAGE_REPO_PASSWORD: ${{ secrets.artifactory_pw }}
      DOCKER_IMAGE_FULL_NAME: ${{ inputs.registry_addr }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
      DOCKERFILE_PATH: ${{ inputs.dockerfile_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & push images
        run: |
          pwd
          cd ${{ env.DOCKERFILE_PATH }}
          docker login ${{ env.IMAGE_REPO }} -u ${{ env.IMAGE_REPO_USER }} -p ${{ env.IMAGE_REPO_PASSWORD }}
          docker build --network host -t ${{ env.DOCKER_IMAGE_FULL_NAME }} -f Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_FULL_NAME }}
          docker rmi ${{ env.DOCKER_IMAGE_FULL_NAME }} || true
