name: Workflow Call Setup VPN Gateway

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      ssh_host_name:
        required: true
        type: string
      ssh_host_ip:
        required: false
        type: string
      dry-run:
        required: true
        type: string  # 可以使用 string 类型传入 "true" 或 "false"

    secrets:
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SUDO_PASSWORD:
        required: true
      ANSIBLE_VAULT_PASSWORD:
        required: true
      GLOBAL_GATEWAY_PRIVATE_KEY:
        required: true
      CN_GATEWAY_PUBLIC_KEY:
        required: true
      DESKTOP_MACBOOK_PUBLIC_KEY:
        required: true
      GLOBAL_K3S_SERVER_PUBLIC_KEY:
        required: true
      GLOBAL_K3S_SERVER_DB_PUBLIC_KEY:
        required: true

jobs:
  init-vpn-gateway:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ inputs.domain }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST_IP: ${{ inputs.ssh_host_ip }}
      SSH_HOST_NAME: ${{ inputs.ssh_host_name }}
      SSH_HOST_DOMAIN: "${{ inputs.ssh_host_name }}.${{ inputs.domain }}"
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      GLOBAL_GATEWAY_PRIVATE_KEY: ${{ secrets.GLOBAL_GATEWAY_PRIVATE_KEY }}
      CN_GATEWAY_PUBLIC_KEY: ${{ secrets.CN_GATEWAY_PUBLIC_KEY }}
      DESKTOP_MACBOOK_PUBLIC_KEY: ${{ secrets.DESKTOP_MACBOOK_PUBLIC_KEY }}
      GLOBAL_K3S_SERVER_PUBLIC_KEY: ${{ secrets.GLOBAL_K3S_SERVER_PUBLIC_KEY }}
      GLOBAL_K3S_SERVER_DB_PUBLIC_KEY: ${{ secrets.GLOBAL_K3S_SERVER_DB_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Pre Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq
          pip3 install ansible jinja2 hvac
          ansible-galaxy collection install community.hashi_vault
          echo "${{ env.ANSIBLE_VAULT_PASSWORD }}" >> ~/.vault_password && sudo chmod 0644 ~/.vault_password

      - name: Extract SSH Host IP and Set as Env Variable
        run: |
          if [ -n "${{ inputs.ssh_host_ip }}" ]; then
            echo "SSH_HOST_IP=${{ inputs.ssh_host_ip }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Update playbook hosts
        run: |
          python scripts/dynamic_inventory.py "vpn-gateway:${{ env.SSH_HOST_DOMAIN }}:${{ env.SSH_HOST_IP }}"
        working-directory: ansible/

      - name: Setup VPN Gateway
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ANSIBLE_OPTIONS=""
          if [ "${{ inputs.dry-run }}" == "true" ]; then
            ANSIBLE_OPTIONS="-D -C"
          fi
          ansible-playbook -i hosts/inventory playbooks/init_vpn_gateway.yml $ANSIBLE_OPTIONS \
              -e "domain=${{inputs.domain}}"                                                  \
              -e "ansible_become_pass=${{ env.SUDO_PASSWORD }}"                               \
              -e "cluster_name=${{inputs.ssh_host_name}}"                                     \
              -e "ansible_vault_password=${{ env.ANSIBLE_VAULT_PASSWORD }}"                   \
              -e "localhost_private_key=${{ env.GLOBAL_GATEWAY_PRIVATE_KEY }}"                \
              -e 'host_keys={
                "cn_gateway_public_key": "${{ env.CN_GATEWAY_PUBLIC_KEY }}",
                "desktop_macbook_public_key": "${{ env.DESKTOP_MACBOOK_PUBLIC_KEY }}",
                "global_k3s_server_public_key": "${{ env.GLOBAL_K3S_SERVER_PUBLIC_KEY }}",
                "global_k3s_server_db_public_key": "${{ env.GLOBAL_K3S_SERVER_DB_PUBLIC_KEY }}"
              }'
        working-directory: ansible/
