name: Workflow Call Setup Harbor Server
on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      ssh_host_ip:
        required: false
        type: string
      ssh_host_name:
        required: true
        type: string
      ssh_host_domain:
        required: false
        type: string
    secrets:
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      ANSIBLE_VAULT_PASSWORD:
        required: true
      OSS_AK:
        required: true
      OSS_SK:
        required: true
      SUDO_PASSWORD:
        required: false

jobs:
  init-harbor-server:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ inputs.domain }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Pre Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq
          pip3 install ansible jinja2 hvac
          ansible-galaxy collection install community.hashi_vault
          echo "${{ env.ANSIBLE_VAULT_PASSWORD }}" >> ~/.vault_password && sudo chmod 0644 ~/.vault_password

      - name: Set Env Variable
        run: |
          if [ -n "${{ inputs.ssh_host_ip }}" ]; then
            echo "SSH_HOST_IP=${{ inputs.ssh_host_ip }}" >> $GITHUB_ENV
          fi
          if [ -n "${{ inputs.ssh_host_domain }}" ]; then
            echo "SSH_HOST_DOMAIN=${{ inputs.ssh_host_domain }}" >> $GITHUB_ENV
          else
            echo "SSH_HOST_DOMAIN=${{ inputs.ssh_host_name }}.${{ inputs.domain }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Update playbook hosts
        run: |
          bash scripts/ansible_playbook_hosts_setup.sh
        working-directory: ansible/ 

      - name: Setup Harbor Server 
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts/inventory init_harbor_server       \
                           -e "backend_type=oss"                       \
                           -e "oss_ak=${{secrets.OSS_AK}}"             \
                           -e "oss_sk=${{secrets.OSS_SK}}"             \
                           -e "cluster_name=${{inputs.ssh_host_name}}" \
                           -e "domain=${{inputs.domain}}" -D
        working-directory: ansible/
