name: Workflow Call Set ArgoCD for helmfile

on:
  workflow_call:
    inputs:
      helmfile:
        required: true
        type: string
      namespace:
        required: true
        type: string
      config_repo:
        required: true
        type: string
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  setup-argocd-crd:
    runs-on: ubuntu-latest

    container:
      image: artifact.onwalk.net/public/base/alpine-chart-builder:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set kube config
        run: |
          mkdir -p $HOME/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > $HOME/.kube/config

      - name: Set ArgoCD CRD
        run: |
          function create_argocd_application() {
              local helmfile=$1
              local namespace=$2
              local config_repo=$3
              local app_name=$(basename $helmfile .yml)  # 移除扩展名 .yml
              # 定义 YAML 字符串并将其传递给后续命令
              cat <<EOF | kubectl apply -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${app_name}-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${config_repo}
    path: ${helmfile}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOF
          }
          create_argocd_application "${{ inputs.helmfile }}" "${{ inputs.namespace }}" "${{ inputs.config_repo }}"
